zpool_SOURCES = \
	zpool_iter.c \
	zpool_main.c \
	zpool_util.c \
	zpool_util.h \
	freebsd_zpool_vdev.c

objs = \
	zpool_iter.o \
	zpool_main.o \
	zpool_util.o \
	freebsd_zpool_vdev.o

all: zpool

CFLAGS+= -Wno-absolute-value
include $(ZFSBASE)/cmd/Makefile.bsd.inc

zpool: $(objs)
	$(CC) $(LDFLAGS) $(objs) -o zpool
